### ISSUE TITLE
The y_lb library will break the header styling.

### ISSUE THREAD

**Issue by oleh-rymar** [YCloudYUSA/yusaopeny_gated_content#98]
This code attaches the y_lb library to all node pages of the site where the "layout_builder__layout" field is available.`   
 
 if ($node->hasField('layout_builder__layout')) {
      $variables['#attached']['library'][] = 'openy_gated_content/y_lb';
....
    }` 
![Screenshot from 2024-05-24 18-35-31](https://github.com/YCloudYUSA/yusaopeny_gated_content/assets/164229587/0de5e4b3-4dc2-41fd-8cb9-69a226e0cd13)

As a result, the site header looks broken.

Suggested solution: Remove the fixed position from the header block.

**Comment by podarok** [comment]
https://github.com/YCloudYUSA/yusaopeny_gated_content/releases/tag/1.9.1
